version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgressql-date:/var/lib/postgresql/data
    networks:
      - postgres-network
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "16543:80"
    depends_on:
      - postgresql
    networks:
      - postgres-network
    links:
      - postgresql

  redis-golang:
    image: "redis:alpine"
    container_name: redis-golang
    ports:
      - "6379:6379"
    networks:
      - redis-network
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis-golang
    ports:
      - "8083:8081"
    networks:
      - redis-network

networks:
  postgres-network:
    driver: bridge
  redis-network:
    driver: bridge
volumes:
  postgressql-date:

       